FROM python:3.8.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    python -m spacy download en_core_web_sm

COPY backend/ .

EXPOSE 5000

CMD ["python", "customApp.py"]
